/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hearthstoneclicker;

import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *
 * @author AlexJupe
 */
public class HomeFrame extends javax.swing.JFrame {
public static int gold = 0;
public static int dust = 0;
public static int goldPerClick = 1;
public static int goldPerSecond = 0;
public static int progress = 0;
public static int exp =0;
public static int rank = 25;
public static int levelUp =0;
public static int multiplier = 20;

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelHome = new javax.swing.JLabel();
        jButtonGold = new javax.swing.JButton();
        jLabelGold = new javax.swing.JLabel();
        jLabelGoldAmt = new javax.swing.JLabel();
        jButtonShop = new javax.swing.JButton();
        jButtonPacks = new javax.swing.JButton();
        jLabelDust = new javax.swing.JLabel();
        jLabelDustAmt = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelStats = new javax.swing.JLabel();
        jLabelGoldPerClick = new javax.swing.JLabel();
        jLabelGPCAmt = new javax.swing.JLabel();
        jLabelGPS = new javax.swing.JLabel();
        jLabelGPSAmt = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelRank = new javax.swing.JLabel();
        jLabelRankIcon = new javax.swing.JLabel();
        jLabelExp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        jLabelHome.setText("Home");

        jButtonGold.setText("Gold button");
        jButtonGold.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGoldMouseClicked(evt);
            }
        });
        jButtonGold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoldActionPerformed(evt);
            }
        });

        jLabelGold.setText("Gold:");

        jLabelGoldAmt.setText("0");

        jButtonShop.setText("Shop");
        jButtonShop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonShopMouseClicked(evt);
            }
        });

        jButtonPacks.setText("Packs");
        jButtonPacks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPacksMouseClicked(evt);
            }
        });

        jLabelDust.setText("Dust");

        jLabelDustAmt.setText("0");

        jLabelStats.setText("Stats");

        jLabelGoldPerClick.setText("Gold per click:");

        jLabelGPS.setText("Gold per sec:");

        jLabelGPSAmt.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabelStats))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelGoldPerClick)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelGPCAmt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelGPS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelGPSAmt)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelStats)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGoldPerClick)
                    .addComponent(jLabelGPCAmt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGPS)
                    .addComponent(jLabelGPSAmt))
                .addContainerGap(278, Short.MAX_VALUE))
        );

        jLabelRank.setText("Rank");

        jLabelRankIcon.setText("25");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelExp)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelRank)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelRankIcon)))
                .addGap(71, 71, 71))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRank, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRankIcon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabelExp)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabelHome, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jButtonGold, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDust)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelDustAmt))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelGold)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelGoldAmt)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonShop)
                            .addComponent(jButtonPacks))
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelHome, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonGold, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jButtonShop)
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelGold)
                                    .addComponent(jLabelGoldAmt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelDust)
                                    .addComponent(jLabelDustAmt))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonPacks)
                                .addGap(59, 59, 59))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 39, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGoldActionPerformed

    private void jButtonGoldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGoldMouseClicked
        // TODO add your handling code here:
       gold = gold + goldPerClick;
       exp = exp + goldPerClick;
       jLabelGoldAmt.setText(gold + "");
       progressBar();
       jLabelExp.setText("" + exp +"/" + levelUp);
       
      
    }//GEN-LAST:event_jButtonGoldMouseClicked

    private void jButtonShopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonShopMouseClicked
        // TODO add your handling code here:
        //open the packs frame
        new ShopFrame().setVisible(true);
    }//GEN-LAST:event_jButtonShopMouseClicked

    private void jButtonPacksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPacksMouseClicked
        // TODO add your handling code here:
        
        //open the packs frame
        new PackFrame().setVisible(true);
    }//GEN-LAST:event_jButtonPacksMouseClicked

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
        jLabelGoldAmt.setText("" + gold);
        jLabelDustAmt.setText("" + dust);
        jLabelGPCAmt.setText("" + goldPerClick);
        jLabelGPSAmt.setText("" + goldPerSecond);
        progressBar();
        
    }//GEN-LAST:event_formMouseEntered

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        GoldPerSecond gps = new GoldPerSecond();
        gps.start();
        System.out.println("started");
        jLabelGPCAmt.setText("" + goldPerClick);
        jLabelGPSAmt.setText("" + goldPerSecond);
    }//GEN-LAST:event_formWindowOpened

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        progressBar();
        jLabelExp.setText("" + exp +"/" + levelUp);
    }//GEN-LAST:event_formMouseMoved

    public void progressBar(){
        levelUp = rank * multiplier;
        if(exp >= levelUp){
            rank = rank -1;
            jLabelRankIcon.setText("" + rank);
            multiplier = multiplier * 2;
            jLabelExp.setText("" + exp +"/" + levelUp);
        }
        levelUp = rank * multiplier;
        progress = exp/levelUp * 100;
       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

         
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
                
            }
        });
        
        
    }
    
    class GoldPerSecond extends Thread{
        public void run(){
            do{
              gold = gold + goldPerSecond;
              exp = exp + goldPerSecond;
              jLabelGoldAmt.setText("" + gold);
                try {
                    sleep(1000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(HomeFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }while(true);
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGold;
    private javax.swing.JButton jButtonPacks;
    private javax.swing.JButton jButtonShop;
    private javax.swing.JLabel jLabelDust;
    private javax.swing.JLabel jLabelDustAmt;
    private javax.swing.JLabel jLabelExp;
    private javax.swing.JLabel jLabelGPCAmt;
    private javax.swing.JLabel jLabelGPS;
    private javax.swing.JLabel jLabelGPSAmt;
    private javax.swing.JLabel jLabelGold;
    public javax.swing.JLabel jLabelGoldAmt;
    private javax.swing.JLabel jLabelGoldPerClick;
    private javax.swing.JLabel jLabelHome;
    private javax.swing.JLabel jLabelRank;
    private javax.swing.JLabel jLabelRankIcon;
    private javax.swing.JLabel jLabelStats;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
