/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hearthstoneclicker;

import static hearthstoneclicker.HomeFrame.dust;
import static hearthstoneclicker.HomeFrame.gold;
import static hearthstoneclicker.HomeFrame.goldPerClick;
import static hearthstoneclicker.HomeFrame.goldPerSecond;
import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author AlexJupe
 */
public class ShopFrame extends javax.swing.JFrame {
    private Component frame;

    /**
     * Creates new form ShopFrame
     */
    public ShopFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelShop = new javax.swing.JLabel();
        jLabelGold = new javax.swing.JLabel();
        jLabelDust = new javax.swing.JLabel();
        jLabelGoldAmtShop = new javax.swing.JLabel();
        jLabelDustAmt = new javax.swing.JLabel();
        jButtonGPC = new javax.swing.JButton();
        jButtonGPS = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });

        jLabelShop.setText("Shop");

        jLabelGold.setText("Gold");

        jLabelDust.setText("Dust");

        jButtonGPC.setText("Upgrade Gold Per Click");
        jButtonGPC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGPCMouseClicked(evt);
            }
        });

        jButtonGPS.setText("Upgrade Gold Per Second");
        jButtonGPS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGPSMouseClicked(evt);
            }
        });

        jLabel1.setText("40 dust");

        jLabel2.setText("40 dust");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDust)
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabelGold)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDustAmt)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelGoldAmtShop)
                                .addGap(173, 173, 173)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonGPS)
                                    .addComponent(jLabelShop)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButtonGPC))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel1)
                        .addGap(167, 167, 167)
                        .addComponent(jLabel2)))
                .addContainerGap(241, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabelShop))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelGold)
                            .addComponent(jLabelGoldAmtShop))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDust)
                            .addComponent(jLabelDustAmt))))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGPC)
                    .addComponent(jButtonGPS))
                .addContainerGap(221, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
        jLabelGoldAmtShop.setText("" + gold);
        jLabelDustAmt.setText("" + dust);
    }//GEN-LAST:event_formMouseEntered

    private void jButtonGPCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGPCMouseClicked
        // TODO add your handling code here:
        if(dust > 39){
        dust = dust - 40;
        jLabelDustAmt.setText("" + dust);
        goldPerClick = goldPerClick + 10;
        }
        else{
            JOptionPane.showMessageDialog(frame,
                    "Not enough dust");
        }
    }//GEN-LAST:event_jButtonGPCMouseClicked

    private void jButtonGPSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGPSMouseClicked
        // TODO add your handling code here:
        if(dust > 39){
        dust = dust - 40;
        jLabelDustAmt.setText("" + dust);
        goldPerSecond = goldPerSecond + 1;
        }
        else{
            JOptionPane.showMessageDialog(frame,
                    "Not enough dust");
        }
        
    }//GEN-LAST:event_jButtonGPSMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShopFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShopFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShopFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShopFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShopFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGPC;
    private javax.swing.JButton jButtonGPS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDust;
    private javax.swing.JLabel jLabelDustAmt;
    private javax.swing.JLabel jLabelGold;
    public javax.swing.JLabel jLabelGoldAmtShop;
    private javax.swing.JLabel jLabelShop;
    // End of variables declaration//GEN-END:variables
}
